version: '3'

services:
  home-site:
    image: deweiliu/home-site:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      args: 
        UPDATE_TIME: $UPDATE_TIME
    ports:
      - 80:80
    container_name: home-site-container