version: '3'

services:
  best-friends:
    image: deweiliu/dewei:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      args: 
        UPDATE_TIME: $UPDATE_TIME
    ports:
      - 80:80
    container_name: dewei-container