pipeline {
    agent {
        label 'deployer-slave-amazon-linux'
    }

    stages {
        stage('CDK Deploy'){
            steps{
                dir('cdk'){
                    sh '''
                    npm install;
                    npm run cdk-deploy;
                    '''
                }
            }
        }
    }
}
